stages:
  - build
  - deploy
  - production

build-job:
  stage: build
  only:
    - develop
    - master
  tags:
    - shell
  script:
    - docker build . -t kesha
    # well, you don't expect me to copy database file every time I build an image?


deploy-job:
  stage: deploy
  only:
    - develop
    - master
  tags:
    - shell
  script:
    - ln -s /var/people.db $CI_PROJECT_DIR/dao/
    - docker-compose up -d
