stages:
  - build
  - deploy
  - production

build-job:
  stage: build
  only:
    - develop
    - master
  tags:
    - shell
  script:
    - docker-compose build
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose push

deploy-job:
  stage: deploy
  only:
    - develop
    - master
  tags:
    - shell
  script:
    - ln -s /var/people.db $CI_PROJECT_DIR/dao/
    - docker-compose up -d
