version: "3"
services:
  kesha:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_MODULE=controller.PersonController:app
    volumes:
      - ./dao/people.db:/var/people.db
    networks:
      - net
    image: registry.miem.hse.ru/857/backend

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.22.0/24
